- id: gitleaks-docker
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Gitleaks
  entry: zricethezav/gitleaks:v8.17.0 protect --verbose --redact --staged
  language: docker_image