# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: gcr.io/shkirmantsev
  # Overrides the image tag whose default is the chart appVersion
  tag: "v1.0.12-f4dd971"
  os: "linux"
  arch: "amd64"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  tokenKey: token
  tokenName: TELE_TOKEN
securityContext:
  privileged: true
imagePullSecrets:
  - name: gcr-json-key
